version: '3.8'

services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - /mnt3/clickhouse:/var/lib/clickhouse
      - ./clickhouse/clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/clickhouse_users.xml:/etc/clickhouse-server/users.xml
    environment:
      - MAX_MEMORY_USAGE=20GB
      - MAX_MEMORY_USAGE_FOR_USER=20GB

volumes:
  clickhouse_data:
