version: '3.8'

services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - /mnt3/clickhouse:/var/lib/clickhouse
      - ${PWD}/clickhouse/clickhouse_config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/clickhouse/clickhouse_users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/clickhouse/clickhouse_docker_related_config.xml:/etc/clickhouse-server/config.d/docker_related_config.xml
    environment:
      - MAX_MEMORY_USAGE=40000000000  # 40GB
      - MAX_MEMORY_USAGE_FOR_USER=40000000000  # 40GB
    command: >
      bash -c "sysctl -w vm.swappiness=10 &&
               clickhouse-server --config-file=/etc/clickhouse-server/config.xml"
volumes:
  clickhouse_data:
