version: '3.8'

services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - /mnt3/clickhouse:/var/lib/clickhouse
      - ${PWD}/clickhouse/clickhouse_config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/clickhouse/clickhouse_users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/clickhouse/clickhouse_docker_related_config.xml:/etc/clickhouse-server/config.d/docker_related_config.xml
    environment:
      - MAX_MEMORY_USAGE=20000000000  # 20GB
      - MAX_MEMORY_USAGE_FOR_USER=20000000000  # 20GB
    deploy:
      resources:
        limits:
          memory: 32G
        reservations:
          memory: 30G
    memswap_limit: 10G
volumes:
  clickhouse_data:
